name: learn-github-actions
on: [push]
jobs:
    build:
        name: builds
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: yarn install
              run: yarn install
            - name: Run Jest
              run: yarn jest
