name: learn-github-actions
on: [push]
jobs:
    build:
        name: builds
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: yarn install
              run: yarn install
            - name: eslint review
              uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review
                  eslint_flags: './**/*.{vue,ts,js}'
            - name: Run Jest
              run: yarn jest
